### ISSUE TITLE
Scheme: scrollbar theme mismatch

### ISSUE THREAD

**Issue by FilipChalupa** [contember/admin#122]
Scrollbar and possibly other native elements don't respect dark theme.

### Now

![image](https://user-images.githubusercontent.com/1045362/149770904-0e68086c-6b0b-4ba4-8585-6acda4a80bf0.png)

### Expected

![image](https://user-images.githubusercontent.com/1045362/149770941-62fa89ac-d23c-4489-b591-26c56163ef74.png)

## Partial solution

```css
:root {
    color-scheme: light dark;
}
.scheme-light {
    color-scheme: light;
}
.scheme-dark {
    color-scheme: dark;
}
```
